spring.application.name=gof-pokemon-service

spring.datasource.url=jdbc:h2:mem:pokemons
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=pass

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
